version: '2'
services:
  php7:
    build: ./docker/php7
    ports:
      - "9000"
    volumes:
      - ./app:/var/www
    working_dir: /var/www
  hub:
    image: "selenium/hub:3.4.0-dysprosium"
  chrome:
    image: "selenium/node-chrome:3.4.0-einsteinium"
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    links:
      - hub
